version: 1.6.5
checkForUpdate: true
spawneggs: true
spawners: false
tamedWolvesGiveMoney: true
defaultLanguage: english
group-multiplier:
  level-1: 1.0
  level-2: 1.0
  level-3: 1.0
  level-4: 1.0
  level-5: 1.0
  operator: 1.0
actions-multipliers:
  isMultipliersAggregate: false
  riding-horse:
    multiplier: 1.0
    isActive: false
    priority: 1
  riding-mule:
    multiplier: 1.0
    isActive: false
    priority: 1
  riding-donkey:
    multiplier: 1.0
    isActive: false
    priority: 1
  riding-pig:
    multiplier: 1.0
    isActive: false
    priority: 1
  riding-strider:
    multiplier: 1.0
    isActive: false
    priority: 1
  fallDamage:
    multiplier: 1.0
    isActive: false
    priority: 1
  longDistance:
    distance: 1.0
    multiplier: 1.0
    isActive: false
    priority: 1
  projectile:
    multiplier: 1.0
    isActive: false
    priority: 1
  noWeapon:
    multiplier: 1.0
    isActive: false
    priority: 1
  mountedMob:
    multiplier: 1.0
    isActive: false
    priority: 1
