version: "1.6.9-Nice-:)" # Current version of M4M. Should update accordingly
checkForUpdate: true # Checks if a new update is available. Version is checked in SpigotMC and take some hours to sync up
spawneggs: true # Boolean if players will get rewarded money for killing mobs spawned in with eggs
spawners: false # Boolean if players will get rewarded money for killing mobs spawned in by a spawner
tamedWolvesGiveMoney: true # Boolean if players will get rewarded money if their tamed wolf kills a mob
defaultLanguage: english # Sets the default language of the server which links up with the messages.yml and will set the language of new users in the users.yml
oldSpawnReasonLogic: true # Boolean if old spawn logic will be used. More documentation in Github.README.md
group-multiplier: # Percentage multiplier which can be updated and group names changed. Permissions are m4m.multiplier.superbad.[group-name]
  level-1: 1.0
  level-2: 1.0
  level-3: 1.0
  level-4: 1.0
  level-5: 1.0
  operator: 1.0
actions-multipliers: # Multipliers
  isMultipliersAggregate: false # If money is added up for each action multiplier 
  riding-horse:
    multiplier: 1.0 # Money multiplier percentage
    isActive: false # Boolean if multiplier is active
    priority: 1 # Priority level for multiplier. The higher the priority, the higher the precedent 
  riding-mule:
    multiplier: 1.0
    isActive: false
    priority: 1
  riding-donkey:
    multiplier: 1.0
    isActive: false
    priority: 1
  riding-pig:
    multiplier: 1.0
    isActive: false
    priority: 1
  riding-strider:
    multiplier: 1.0
    isActive: false
    priority: 1
  fallDamage:
    multiplier: 1.0
    isActive: false
    priority: 1
  longDistance:
    distance: 1.0
    multiplier: 1.0
    isActive: false
    priority: 1
  projectile:
    multiplier: 1.0
    isActive: false
    priority: 1
  noWeapon:
    multiplier: 1.0
    isActive: false
    priority: 1
  mountedMob:
    multiplier: 1.0
    isActive: false
    priority: 1
